name: Matrix Example

on:
  push:
    branches:
      - main

jobs:  
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]
        node: [18, 20]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-verion: ${{ matrix.node }}
      - name: Install Dependencies
        run: npm install
      - name: Build the App
        run: npm run build
