name: Data Passing Workflow
on: [push]
jobs: 
  job1:  
    runs-on: ubuntu-latest
    steps:
    - name: Generate Data
      run: echo "Some data generated in job 1" > data.txt
    - name: Upload data as artifactor
      uses: actions/upload-artifact@v2
      with:
        name: data-artifact
        path: data.txt
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - name: Delete Artifact
      uses: geekyeggo/delete-artifact@v4
      with:  
        name: data-artifact
