name: Build and Publish NPM Package

on:
  push:
    branches:
      - main # Trigger the workflow on push events to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # Checks-out your repository under $GITHUB_WORKSPACE

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Specify the Node.js version
          registry-url: 'https://npm.pkg.github.com' # Set the NPM registry URL
          scope: '@solankiarpan' # Set the scope to your GitHub username or organization
          
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build # Replace with your build command

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}} # Use the GITHUB_TOKEN secret to authenticate
